[package]
name = "leo-resolver"
version = "1.0.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Resolves implicit types in a Leo AST"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

#[dependencies.leo-input]
#path = "../input"
#version = "1.0.3"

[dependencies.leo-imports]
path = "../imports"
version = "1.0.3"

[dependencies.leo-typed]
path = "../typed"
version = "1.0.3"

[dependencies.thiserror]
version = "1.0"
#
#[dependencies.snarkos-algorithms]
#version = "1.1.3"
#default-features = false
#
#[dependencies.snarkos-curves]
#version = "1.1.3"
#default-features = false
#
#[dependencies.snarkos-dpc]
#version = "1.1.3"
#default-features = false
#
#[dependencies.snarkos-errors]
#version = "1.1.3"
#default-features = false
#
#[dependencies.snarkos-models]
#version = "1.1.3"
#default-features = false
#
#[dependencies.snarkos-objects]
#version = "1.1.3"
#default-features = false
#
#[dependencies.snarkos-utilities]
#version = "1.1.3"
#
#[dependencies.rand]
#version = "0.7"
#
#[dependencies.rand_xorshift]
#version = "0.2"
#

#
#[dev-dependencies.snarkos-storage]
#version = "1.1.4"
